apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: secure-apps
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/amahmoodi181188/sharky1.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

